---
abstract: 'full set of array and set operations'
author:
  - 'Sullivan Beck <sbeck@cpan.org>'
build_requires:
  Module::Build: '0.21'
  Storable: '0'
  Test::More: '0'
configure_requires:
  Module::Build: '0.21'
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Array-AsObject
provides:
  Array::AsObject:
    file: lib/Array/AsObject.pm
    version: '1.03'
requires:
  Sort::DataTypes: '0'
  perl: '5.006'
resources:
  license: http://dev.perl.org/licenses/
version: '1.03'
