#!/usr/bin/perl

use strict;
use warnings;
use Array::AsObject;

my $obj = new Array::AsObject;

$obj->list(qw(a b c));

print $obj->exists(qw(a)),"\n";         # 1
print $obj->exists(qw(a c)),"\n";       # 1
print $obj->exists(qw(a d)),"\n";       # 0
print $obj->exists(),"\n";              # 0

$obj->list(qw(a b c),undef);

print $obj->exists(),"\n";              # 1
